# Site
name: 'TechMunching'
description: 'Your daily tech snack'
logo: '/assets/images/logo.webp'
favicon: 'assets/images/logo.webp'
baseurl: ''
disqus: 'techmunching'
email: 'techmunching@gmail.com'
mailchimp-list: 'https://tinyletter.com/TechMunching'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-minifier
  - jekyll-webp
  
authors:
    admin:
      name:           TechMunching
      site:           https://www.techmunching.com
      avatar:         /assets/images/logo
      bio:            "Hi, We are Tech Munching. We hope you love it!"
      email:          techmunching@gmail.com
      twitter:        https://twitter.com/techmunching
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: "TechMunching"
      avatar: /assets/images/logo
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
# highlighter: rouge 

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

# Google Analytics
google_analytics: G-Y7HGWZX785

# plugins:
#   - jekyll-compress-images


# compress_images:
#   images_path: "img/**/*"
#   svgo: false

url: "https://techmunching.com" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap

jekyll-minifier:
  exclude: 'atom.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns

############################################################
# Site configuration for the WebP Generator Plugin
# The values here represent the defaults if nothing is set
webp:
  enabled: true
  
  # The quality of the webp conversion 0 to 100 (where 100 is least lossy)
  quality: 75

  # List of directories containing images to optimize, nested directories will only be checked if `nested` is true
  # By default the generator will search for a folder called `/img` under the site root and process all jpg, png and tiff image files found there.
  img_dir: ["/img"]

  # Whether to search in nested directories or not
  nested: false

  # add ".gif" to the format list to generate webp for animated gifs as well
  formats: [".jpeg", ".jpg", ".png", ".tiff"]

  # File extensions for animated gif files 
  gifs: [".gif"]

  # Set to true to always regenerate existing webp files
  regenerate: false

  # Local path to the WebP utilities to use (relative or absolute)
  # Omit or leave as nil to use the utilities shipped with the gem, override only to use your local install
  webp_path: nil

  # List of files or directories to exclude
  # e.g. custom or hand generated webp conversion files
  exclude: []

  # append '.webp' to filename after original extension rather than replacing it.
  # Default transforms `image.png` to `image.webp`, while changing to true transforms `image.png` to `image.png.webp`
  append_ext: false
############################################################

environment: production

