# Site
name: 'TechMunching'
description: 'Your daily tech snack'
logo: '/assets/images/logo.webp'
favicon: 'assets/images/logo.webp'
baseurl: ''
disqus: 'techmunching'
email: 'techmunching@gmail.com'
mailchimp-list: 'https://tinyletter.com/TechMunching'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-minifier
  
authors:
    admin:
      name:           TechMunching
      site:           https://www.techmunching.com
      avatar:         /assets/images/logo.webp
      bio:            "Hi, We are Tech Munching. We hope you love it!"
      email:          techmunching@gmail.com
      twitter:        https://twitter.com/techmunching
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: "TechMunching"
      avatar: /assets/images/logo.webp
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
# highlighter: rouge 

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

# Google Analytics
google_analytics: G-Y7HGWZX785

# plugins:
#   - jekyll-compress-images


# compress_images:
#   images_path: "img/**/*"
#   svgo: false

url: "https://techmunching.com" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap

jekyll-minifier:
  exclude: 'atom.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns

environment: production

